#!/usr/bin/env bash
#
# Cron-driven pipeline:
#   1. fetch  — pulls wuhu page; skip-if-unchanged handled inside
#   2. export-reach — regenerate frontend/data/reach.json
#   3. commit + push reach.json if it changed (push iron-rule from MEMORY)
#
# Exit non-zero on any failure; cron will email / surface the log.
#
# Crontab entry (Europe/Madrid, summer+winter DST aware via CRON_TZ):
#   CRON_TZ=Europe/Madrid
#   0 20 * * *  /home/ubuntu/.openclaw/workspace/train_crecc/scripts/cron_fetch.sh
#

set -euo pipefail

PROJ="/home/ubuntu/.openclaw/workspace/train_crecc"
LOG="$PROJ/data/cron.log"
TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

cd "$PROJ"

log() { echo "[$TS] $*" | tee -a "$LOG"; }

log "=== cron_fetch start ==="

# Snapshot the current last_updated BEFORE we re-fetch, so we can detect a
# real upstream change. export_reach_json doesn't produce byte-stable output
# across runs (dict ordering etc.), so a plain `git diff` check fires on every
# cron tick and would pollute history. last_updated only changes when the
# upstream snapshot has actually moved.
last_updated_before=$(python3 -c "import sqlite3; c=sqlite3.connect('data/train.db'); print(c.execute(\"SELECT value FROM meta WHERE key='last_updated'\").fetchone()[0] or '')")

# 1. Pull latest from upstream
if ! python3 main.py fetch >> "$LOG" 2>&1; then
    log "ERROR: main.py fetch failed"
    exit 1
fi

# 2. Regenerate reach.json (idempotent)
if ! python3 main.py export-reach >> "$LOG" 2>&1; then
    log "ERROR: main.py export-reach failed"
    exit 2
fi

# 3. Compare last_updated AFTER the fetch. If unchanged, we're done.
last_updated_after=$(python3 -c "import sqlite3; c=sqlite3.connect('data/train.db'); print(c.execute(\"SELECT value FROM meta WHERE key='last_updated'\").fetchone()[0] or '')")
if [ "$last_updated_before" = "$last_updated_after" ]; then
    log "upstream last_updated unchanged ($last_updated_after) — skipping push"
    log "=== cron_fetch end (no-op) ==="
    exit 0
fi
log "upstream last_updated: $last_updated_before -> $last_updated_after"

# 4. Push if reach.json actually changed (it always will if last_updated moved,
# but re-check in case the export wrote the same upstream timestamp as a
# no-op re-run).
if git diff --quiet -- frontend/data/reach.json; then
    log "reach.json unchanged despite last_updated bump — nothing to commit"
    log "=== cron_fetch end (no-op) ==="
    exit 0
fi

git add frontend/data/reach.json
git commit -m "data(refresh): sync reach.json — upstream ${last_updated_after}" \
    -m "Auto-generated by scripts/cron_fetch.sh (Europe/Madrid 20:00 daily).
- last_updated bumped from $last_updated_before to $last_updated_after
- reach.json regenerated via main.py export-reach" \
    >> "$LOG" 2>&1

if ! git push origin main >> "$LOG" 2>&1; then
    log "ERROR: git push failed (commit landed locally; manual push needed)"
    exit 3
fi

log "reach.json pushed to origin/main"
log "=== cron_fetch end (updated) ==="
